-- AlterTable
ALTER TABLE "Reservation" ALTER COLUMN "startDate" SET DATA TYPE DATE,
ALTER COLUMN "endDate" SET DATA TYPE DATE;

-- AlterTable
ALTER TABLE "RoomInventory" ALTER COLUMN "date" SET DATA TYPE DATE;
